create table if not exists users (
  id text primary key,
  name text not null,
  email text not null unique,
  role text not null,
  active boolean not null default true,
  "needsPasswordChange" boolean
);

create table if not exists professionals (
  id text primary key,
  name text not null,
  specialty text not null,
  phone text,
  email text,
  color text not null,
  active boolean not null default true,
  "workingHoursStart" text not null,
  "workingHoursEnd" text not null,
  "workingDays" jsonb not null default '[]',
  "defaultDuration" integer not null default 30,
  notes text,
  "calUserId" integer,
  "calUsername" text,
  "calEventTypeId" integer,
  "calTeamId" integer,
  "calOrgId" integer,
  "calAccountType" text,
  "calApiKeyEnvVar" text,
  timezone text,
  "calConnected" boolean not null default false
);

create table if not exists patients (
  id text primary key,
  name text not null,
  phone text not null,
  "normalizedPhone" text,
  birthdate text,
  cpf text,
  email text,
  address jsonb,
  "importantNotes" text not null default '',
  "quickNotes" text not null default '',
  "absencesCount" integer not null default 0,
  "lastAppointmentDate" text,
  history jsonb not null default '[]'
);

create table if not exists contacts (
  id text primary key,
  name text not null,
  phone text not null,
  "normalizedPhone" text not null,
  email text,
  "whatsappOptIn" boolean not null default true,
  "patientId" text references patients(id) on delete set null,
  tags jsonb not null default '[]',
  notes text not null default '',
  source text not null default 'manual',
  "createdAt" text not null,
  "updatedAt" text not null
);

create table if not exists appointments_cache (
  id text primary key,
  "patientId" text,
  "patientName" text not null,
  "patientPhone" text,
  "professionalId" text references professionals(id) on delete set null,
  date text not null,
  time text not null,
  "endTime" text not null,
  duration integer not null default 30,
  type text not null,
  status text not null,
  notes text not null default '',
  "calBookingUid" text unique,
  "calStatus" text,
  source text,
  "startAt" text,
  "endAt" text,
  timezone text
);

create table if not exists time_off (
  id text primary key,
  "professionalId" text not null references professionals(id) on delete cascade,
  "calOooId" integer,
  start text not null,
  "end" text not null,
  reason text not null default 'unspecified',
  notes text not null default '',
  source text not null default 'internal'
);

create table if not exists clinic_settings (
  id text primary key default 'default',
  "workingHoursStart" text not null,
  "workingHoursEnd" text not null,
  "workingDays" jsonb not null default '[]',
  "defaultDuration" integer not null default 30,
  "gapDuration" integer not null default 0,
  "appointmentTypes" jsonb not null default '[]',
  "clinicName" text not null,
  "clinicPhone" text not null,
  "clinicEmail" text not null,
  "clinicAddress" text not null,
  timezone text not null default 'America/Sao_Paulo',
  "calAccountType" text not null default 'individual',
  "calTeamId" integer,
  "calOrgId" integer,
  "n8nWebhookUrl" text
);

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  payload jsonb not null default '{}',
  created_at timestamptz not null default now()
);
